-- 1. 메뉴 데이터 입력 (ID=1, 아메리카노, 4000원)
-- STOCK_ID는 임시로 1로 설정합니다. (STOCK-SERVICE에도 ID=1인 재고를 넣어두면 좋습니다)
INSERT INTO MENUS (ID, NAME, DESCRIPTION, PRICE, STOCK_ID)
VALUES (1, '아메리카노', '아메리카노', 4000, 1);

-- 2. 옵션 그룹 데이터 입력 (온도, 사이즈)
INSERT INTO OPTION_GROUPS (ID, MENU_ID, NAME) VALUES (1, 1, '온도');
INSERT INTO OPTION_GROUPS (ID, MENU_ID, NAME) VALUES (2, 1, '사이즈');

-- 3. 옵션 상세 데이터 입력
-- (ID를 지정해서 넣어야 JS의 하드코딩된 ID와 맞출 수 있습니다)
INSERT INTO OPTIONS (ID, GROUP_ID, NAME, ADDITIONAL_PRICE) VALUES (1, 1, 'Hot', 0);
INSERT INTO OPTIONS (ID, GROUP_ID, NAME, ADDITIONAL_PRICE) VALUES (2, 1, 'Ice', 0);
INSERT INTO OPTIONS (ID, GROUP_ID, NAME, ADDITIONAL_PRICE) VALUES (3, 2, 'Regular', 0);
INSERT INTO OPTIONS (ID, GROUP_ID, NAME, ADDITIONAL_PRICE) VALUES (4, 2, 'Size Up', 500);